gh: Add e2e job
Signed-off-by: Enrique Llorente <ellorent@redhat.com>

diff --git a/.github/workflows/checks.yaml b/.github/workflows/checks.yaml
--- a/.github/workflows/checks.yaml
+++ b/.github/workflows/checks.yaml
@@ -38,3 +38,30 @@ jobs:
 
     - name: Test
       run: ENVTEST_VERSION="release-0.17" make test
+  e2e:
+    runs-on: ubuntu-latest
+    steps:
+
+    - uses: actions/checkout@v3
+
+    - name: Set up Go
+      uses: actions/setup-go@v3
+      with:
+        go-version-file: 'go.mod'
+
+    - name: Start cluster
+      env:
+        KIND_ALLOW_SYSTEM_WRITES: true
+      run: make cluster-up
+
+    - name: Sync cluster
+      run: make cluster-sync
+
+    - name: Run e2e tests
+      run: make test-e2e
+
+    - uses: actions/upload-artifact@v4  # upload test results
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: test-e2e-results
+        path: .output/*.xml
